"""Regenerate the site icons: the main one ("SR") and the /chess one (a knight).

Run:  python3 scripts/icons.py        (needs fontTools: pip install fonttools)
Writes a vector SVG favicon plus 32px and 180px PNGs for each:
  public/favicon.svg          public/assets/favicon-32.png        public/assets/apple-touch-icon.png
  public/assets/chess-icon.svg public/assets/chess-favicon-32.png  public/assets/chess-apple-touch-icon.png
Letters are Barlow Condensed ExtraBold, the site's heading face (fetched from Google Fonts);
the knight is DejaVu Sans (fc-match). SVG paths and PNGs come from the same outlines and the
same placement, so every size matches. Apple touch icons are full-bleed: iOS rounds them itself.
"""
import re
import subprocess
import tempfile
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont

BG, TEXT, GREEN, BOARD = '#080b10', '#e9eef7', '#6edaa0', '#263142'
CSS = 'https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@800&display=swap'
SS = 8  # PNG supersampling


def num(v):
    return f'{v:.2f}'.rstrip('0').rstrip('.')


def run_of(font_path, text):
    """The glyphs for `text` with their advances (font units)."""
    font = TTFont(font_path)
    cmap, glyph_set = font.getBestCmap(), font.getGlyphSet()
    names = [cmap[ord(ch)] for ch in text]
    return {
        'path': font_path, 'units': font['head'].unitsPerEm,
        'glyphs': [(ch, glyph_set[n], font['hmtx'][n][0]) for ch, n in zip(text, names)]
    }


def place(run, height, cx, cy):
    """Scale a run so its ink is `height` tall and centre that ink on (cx, cy) in the
    32×32 icon (y down). Returns scale, glyph origins, baseline and the ink box."""
    x, origins = 0, []
    x0 = y0 = float('inf')
    x1 = y1 = float('-inf')
    for ch, glyph, advance in run['glyphs']:
        pen = BoundsPen(None)
        glyph.draw(pen)
        if pen.bounds:
            a, b, c, d = pen.bounds
            x0, y0, x1, y1 = min(x0, x + a), min(y0, b), max(x1, x + c), max(y1, d)
        origins.append(x)
        x += advance
    k = height / (y1 - y0)
    ox = cx - k * (x0 + x1) / 2
    baseline = cy + k * (y0 + y1) / 2          # font y points up, icon y points down
    ink = (ox + k * x0, baseline - k * y1, ox + k * x1, baseline - k * y0)
    return {'run': run, 'k': k, 'xs': [ox + k * gx for gx in origins], 'baseline': baseline, 'ink': ink}


def svg_path(placed):
    parts = []
    for (ch, glyph, _), x in zip(placed['run']['glyphs'], placed['xs']):
        pen = SVGPathPen(None, ntos=num)
        glyph.draw(TransformPen(pen, (placed['k'], 0, 0, -placed['k'], x, placed['baseline'])))
        parts.append(pen.getCommands())
    return ' '.join(parts)


def png(out, px, bg, placed, fill, rects=(), rounded=True):
    size = px * SS
    p = size / 32
    img = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    if rounded:
        d.rounded_rectangle([0, 0, size - 1, size - 1], radius=7 * p, fill=bg)
    else:
        d.rectangle([0, 0, size - 1, size - 1], fill=bg)
    run = placed['run']
    font = ImageFont.truetype(run['path'], max(1, round(placed['k'] * run['units'] * p)))
    for (ch, _, _), x in zip(run['glyphs'], placed['xs']):
        d.text((x * p, placed['baseline'] * p), ch, font=font, fill=fill, anchor='ls')
    for x0, y0, x1, y1, colour in rects:
        d.rectangle([x0 * p, y0 * p, x1 * p, y1 * p], fill=colour)
    img.resize((px, px), Image.LANCZOS).save(out, optimize=True)
    print('wrote', out, (px, px))


def write_svg(out, comment, bg, placed, fill, rects=()):
    extra = ''.join(
        f'\n  <rect x="{num(x0)}" y="{num(y0)}" width="{num(x1 - x0)}" height="{num(y1 - y0)}" fill="{c}"/>'
        for x0, y0, x1, y1, c in rects
    )
    Path(out).write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">\n'
        f'  <!-- {comment} — generated by scripts/icons.py -->\n'
        f'  <rect width="32" height="32" rx="7" fill="{bg}"/>\n'
        f'  <path fill="{fill}" d="{svg_path(placed)}"/>{extra}\n'
        '</svg>\n'
    )
    print('wrote', out)


with tempfile.TemporaryDirectory() as tmp:
    css = subprocess.run(['curl', '-s', '-A', 'Mozilla/4.0', CSS], capture_output=True, text=True).stdout
    barlow = Path(tmp, 'barlow-condensed-800.ttf')
    subprocess.run(['curl', '-s', '-o', str(barlow), re.findall(r'https://[^)]+\.ttf', css)[0]], check=True)
    dejavu = subprocess.run(['fc-match', '-f', '%{file}', 'DejaVu Sans'], capture_output=True, text=True).stdout

    # main: "SR" with the site's green underline
    sr = place(run_of(str(barlow), 'SR'), height=14.5, cx=16, cy=14.2)
    bar = (sr['ink'][0], 22.6, sr['ink'][2], 25.2, GREEN)
    write_svg('public/favicon.svg', 'SR in Barlow Condensed, green underline', BG, sr, TEXT, [bar])
    png('public/assets/favicon-32.png', 32, BG, sr, TEXT, [bar])
    png('public/assets/apple-touch-icon.png', 180, BG, sr, TEXT, [bar], rounded=False)

    # /chess: a white knight on the board's dark square colour
    knight = place(run_of(dejavu, '♞'), height=21, cx=16, cy=16.3)
    write_svg('public/assets/chess-icon.svg', 'a knight on the crowd-chess board colour', BOARD, knight, TEXT)
    png('public/assets/chess-favicon-32.png', 32, BOARD, knight, TEXT)
    png('public/assets/chess-apple-touch-icon.png', 180, BOARD, knight, TEXT, rounded=False)
